# Generated by Django 6.0.4 on 2026-09-03 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_member_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
