# Generated by Django 6.0.4 on 2026-09-03 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_member_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('chama', 'Chama / Table Banking Meeting'), ('church', 'Church Service / Harambee'), ('funeral', 'Funeral / Burial'), ('youth', 'Youth / Sports Tournament'), ('women', 'Women Group Baraza'), ('market', 'Market Baraza / Townhall'), ('rally', 'Major Campaign Rally'), ('other', 'Community Function')], default='chama', max_length=50)),
                ('constituency', models.CharField(choices=[('Laikipia East', 'Laikipia East'), ('Laikipia West', 'Laikipia West'), ('Laikipia North', 'Laikipia North')], default='Laikipia West', max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('start_time', models.CharField(default='10:00 AM', max_length=50)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_phone', models.CharField(max_length=20)),
                ('expected_attendance', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_created_by_governor', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Secretariat Review'), ('attending', 'Governor Attending in Person'), ('delegated', 'Sending Representative / Delegate'), ('declined', 'Declined / Regrets Sent')], default='pending', max_length=50)),
                ('delegate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delegate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
