# Generated by Django 6.0.4 on 2026-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_campaignfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingagent',
            name='breakfast_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingagent',
            name='breakfast_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollingagent',
            name='lunch_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pollingagent',
            name='lunch_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
