# Generated by Django 6.0.4 on 2026-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pollingagent_breakfast_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='custom_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='source',
            field=models.CharField(choices=[('field_mobilizer', 'Field Mobilizer'), ('social_media', 'Social Media'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('x_twitter', 'X / Twitter'), ('website', 'Website')], default='field_mobilizer', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='volunteer_role',
            field=models.CharField(blank=True, choices=[('digital_champion', 'Digital Champion'), ('election_volunteer', 'Election Day Volunteer'), ('boda_transport', 'Boda-Boda Transport'), ('general_supporter', 'General Supporter'), ('custom', 'Other / Custom')], max_length=50, null=True),
        ),
    ]
