# Generated by Django 6.0.4 on 2026-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_opted_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='opted_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
