# Generated by Django 6.0.4 on 2026-09-22 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_member_is_opted_out_member_opted_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assigned_polling_centre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='assigned_sub_county',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='assigned_ward',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='campaign_role',
            field=models.CharField(choices=[('governor', 'Governor Aspirant'), ('county_manager', 'County Campaigns Manager'), ('sub_county_coordinator', 'Sub-County Coordinator'), ('ward_coordinator', 'Ward Coordinator'), ('polling_centre_coordinator', 'Polling Centre Coordinator'), ('pillar', 'Campaign Pillar'), ('station_mobilizer', 'Polling Station Mobilizer')], db_index=True, default='station_mobilizer', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='pillar_category',
            field=models.CharField(choices=[('none', 'None'), ('youth', 'Youth Pillar'), ('women', 'Women Pillar'), ('elders_business', 'Elders & Business Pillar'), ('special_interest', 'Special Interest Pillar')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
